In [1]:
import prettymetrics
import pandas as pd

In [2]:
from prettymetrics.supervised import LazyClassifier
from sklearn.model_selection import train_test_split

In [3]:
df= pd.read_csv('../examples/datasets/drug200.csv')

In [4]:
df.head()

   Age Sex      BP Cholesterol  Na_to_K   Drug
0   23   F    HIGH        HIGH    25.36  DrugY
1   47   M     LOW        HIGH    13.09  drugC
2   47   M     LOW        HIGH    10.11  drugC
3   28   F  NORMAL        HIGH     7.80  drugX
4   61   F     LOW        HIGH    18.04  DrugY

In [5]:
df.isnull().sum()

Age            0
Sex            0
BP             0
Cholesterol    0
Na_to_K        0
Drug           0
dtype: int64

In [9]:
from sklearn.preprocessing import LabelEncoder

Sex_le = LabelEncoder()
BP_le  = LabelEncoder()
Cholesterol_le = LabelEncoder()
Drug_le = LabelEncoder()

df['Sex'] = sex_le.fit_transform(df.Sex)
df['BP'] = BP_le.fit_transform(df.BP)
df['Cholesterol'] = Cholesterol_le.fit_transform(df.Cholesterol)
df['Drug'] = Drug_le.fit_transform(df.Drug)

In [12]:
df.head()

   Age  Sex  BP  Cholesterol  Na_to_K  Drug
0   23    0   0            0    25.36     0
1   47    1   1            0    13.09     3
2   47    1   1            0    10.11     3
3   28    0   2            0     7.80     4
4   61    0   1            0    18.04     0

In [13]:
X = df.drop(['Drug'], axis = 1)
Y = df['Drug']

In [14]:
from sklearn.model_selection import train_test_split

X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size=0.15)

In [15]:
X_train

     Age  Sex  BP  Cholesterol  Na_to_K
143   74    1   0            1    15.44
109   23    1   2            0    16.85
74    31    1   0            1    17.07
92    29    0   0            0    29.45
154   37    1   1            1    16.72
..   ...  ...  ..          ...      ...
165   38    1   1            0    18.30
39    15    1   2            0     9.08
135   74    1   1            1    11.94
183   36    0   0            1    15.49
38    39    0   2            1     9.71

[170 rows x 5 columns]

In [16]:
clf = LazyClassifier(verbose=0,ignore_warnings=True, custom_metric=None)
models,predictions = clf.fit(X_train, X_test, Y_train, Y_test)

print(models)

100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████| 43/43 [00:10<00:00,  4.15it/s]

                                Accuracy  Balanced Accuracy ROC AUC  F1 Score  \
Model
LGBMClassifier                      1.00               1.00    None      1.00
XGBClassifier                       1.00               1.00    None      1.00
DecisionTreeClassifier              1.00               1.00    None      1.00
RandomForestClassifier              1.00               1.00    None      1.00
GradientBoostingClassifier          1.00               1.00    None      1.00
HistGradientBoostingClassifier      1.00               1.00    None      1.00
BaggingClassifier                   1.00               1.00    None      1.00
SVC                                 0.97               0.99    None      0.97
MLPClassifier                       0.97               0.99    None      0.97
ExtraTreesClassifier                0.97               0.99    None      0.97
LogisticRegressionCV                0.97               0.99    None      0.97
GaussianProcessClassifier           0.97               0.99    None      0.97
LabelPropagation                    0.97               0.99    None      0.97
LabelSpreading                      0.97               0.99    None      0.97
LinearSVC                           0.93               0.98    None      0.94
LogisticRegression                  0.93               0.98    None      0.94
LinearDiscriminantAnalysis          0.90               0.96    None      0.91
KNeighborsClassifier                0.87               0.94    None      0.87
GaussianNB                          0.80               0.93    None      0.84
SGDClassifier                       0.97               0.90    None      0.96
NearestCentroid                     0.77               0.90    None      0.80
ExtraTreeClassifier                 0.93               0.89    None      0.94
CalibratedClassifierCV              0.90               0.88    None      0.90
Perceptron                          0.93               0.79    None      0.92
BernoulliNB                         0.87               0.75    None      0.87
PassiveAggressiveClassifier         0.87               0.68    None      0.86
RidgeClassifier                     0.87               0.68    None      0.85
RidgeClassifierCV                   0.87               0.68    None      0.85
AdaBoostClassifier                  0.90               0.60    None      0.87
QuadraticDiscriminantAnalysis       0.03               0.20    None      0.00
DummyClassifier                     0.57               0.20    None      0.41

                                Time Taken
Model
LGBMClassifier                        1.40
XGBClassifier                         0.87
DecisionTreeClassifier                0.03
RandomForestClassifier                0.38
GradientBoostingClassifier            0.87
HistGradientBoostingClassifier        2.57
BaggingClassifier                     0.09
SVC                                   0.03
MLPClassifier                         0.46
ExtraTreesClassifier                  0.29
LogisticRegressionCV                  1.50
GaussianProcessClassifier             0.63
LabelPropagation                      0.05
LabelSpreading                        0.06
LinearSVC                             0.03
LogisticRegression                    0.06
LinearDiscriminantAnalysis            0.04
KNeighborsClassifier                  0.04
GaussianNB                            0.04
SGDClassifier                         0.05
NearestCentroid                       0.02
ExtraTreeClassifier                   0.02
CalibratedClassifierCV                0.16
Perceptron                            0.04
BernoulliNB                           0.02
PassiveAggressiveClassifier           0.05
RidgeClassifier                       0.03
RidgeClassifierCV                     0.06
AdaBoostClassifier                    0.29
QuadraticDiscriminantAnalysis         0.03
DummyClassifier                       0.03